name: ci
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.6'
          cache: 'npm'
      
      - name: npm CI
        run: npm ci

      - name: npm Check
        run: npm run check

      - name: npm CI
        run: npm test:ci

      - name: npm test
        run: npm run test:ci
